"""Base strategy class."""
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import List, Optional
from datetime import datetime

from forex_bot_platform.data.provider import OHLCV

@dataclass
class TradingSignal:
    """Trading signal generated by a strategy."""
    timestamp: datetime
    action: str  # "buy" or "sell"
    price: float
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    reason: str = ""

class BaseStrategy(ABC):
    """Abstract base class for trading strategies."""
    
    def __init__(self, name: str = "BaseStrategy"):
        self.name = name
    
    @abstractmethod
    def generate_signals(self, data: List[OHLCV]) -> List[TradingSignal]:
        """Generate trading signals from historical data."""
        pass
    
    def calculate_position_size(self, account_balance: float, risk_per_trade: float, 
                                entry_price: float, stop_loss: float) -> float:
        """Calculate position size based on risk management."""
        if stop_loss == 0 or entry_price == stop_loss:
            return 0
        
        risk_amount = account_balance * risk_per_trade
        pips_risk = abs(entry_price - stop_loss)
        
        if pips_risk == 0:
            return 0
        
        position_size = risk_amount / pips_risk
        return round(position_size, 2)